repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: >
            (?x)^(
                docs/assets/.*
            )$
    -   id: check-yaml
        exclude: >
            (?x)^(
                charts.*|
                sam/template.yaml
            )$
    -   id: check-added-large-files
        args: ['--maxkb=2000']
        exclude: post/utils/symspell
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.2.2'
  hooks:
    - id: ruff
      name: linting with Ruff 🐶
      args: [--fix, --exit-non-zero-on-fix]
    # Run the formatter.
    - id: ruff-format
      name: formatting with Ruff 🐶

- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: rye test
      language: system
      pass_filenames: false
      types: [python]
      stages: [commit, push]
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.16.1
  hooks:
    - id: gitleaks
      name: "Making sure you didn't commit any API keys or other secret stuff"